name = "memocean-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-09-23"

# Account ID sẽ được inject từ GitHub Actions
# account_id = ""

compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "R2"
bucket_name = "memocean"

[[d1_databases]]
binding = "DB"
database_name = "memocean"
database_id = "0cd67a7d-e4f0-4b5c-96e4-3c8ee54a8907"

[[kv_namespaces]]
binding = "KV"
id = "8728d1f130a64fd689d06899e2104108"

[vars]
MEMOCEAN_ALLOW_EXTERNAL_LLM = "false"

[env.production]
workers_dev = false

[env.staging]
workers_dev = true

[env.dev]
workers_dev = true

# Secrets sẽ được set qua wrangler secret put trong CI

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
