name = "memocean-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[env.production]
workers_dev = false

[env.staging]
workers_dev = true

[env.dev]
workers_dev = true

[vars]
API_SECRET_KEY = ""

[assets]
directory = "./public"

[build]
command = "pnpm build"
watch_dir = "packages"

[deploy]
command = "pnpm deploy"

[triggers]
crons = []

[observability]
enabled = true
